spring:
    h2:
      console:
        enable: true
        path: /h2-console
        settings:
          trace: false
          web-allow-others: false

spring:

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false